name: Next.js Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: yarn install
        run: |
          yarn install

      - name: yarn lint
        run: |
          yarn next lint

      - name: yarn build
        run: |
          yarn build
